# Generated by Django 5.1.3 on 2024-11-20 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(blank=True, help_text='Enter a short summary or abstract for the post.', verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Select the author of the post.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter the full content of the post.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='journal',
            field=models.CharField(blank=True, help_text='Enter the name of the journal, if applicable.', max_length=255, verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the post was created.', verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Set the status of the post (e.g., Draft or Published).', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter the title of the post.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='volume',
            field=models.CharField(blank=True, help_text='Enter the volume number, if applicable.', max_length=50, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True, help_text='Enter a URL related to the post, if applicable.', verbose_name='Website'),
        ),
    ]
